[time]
disabled = false
format = '[$time ]($style)'
time_format = '%I:%M'

[battery]
charging_symbol = 'âš¡ï¸'
discharging_symbol = 'ğŸ’€ '

[[battery.display]]
threshold = 10
style = 'bold red'

[[battery.display]]
threshold = 30
style = 'bold yellow'

[git_branch]
symbol = 'îœ¥ '

[c]
detect_extensions = ["c", "h", "cpp", "cc", "hh", "hpp"]
